-- Ensure curriculum_fact_images.id is generated by default.
-- This prevents NULL id insert failures when callers omit the id column.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.curriculum_fact_images
    ALTER COLUMN id SET DEFAULT gen_random_uuid();
